In [ ]:
import pandas as pd
d = {
    1: [2, 4, 2, 4, 2, 4],
    2: [2, 4, 2, 4, 2, 4],
    3: [2, 4, 2, 4, 2, 4],
    14: [2, 4, 2, 4, 2, 4],
    5: [2, 4, 2, 4, 2, 4]
    }
df = pd.DataFrame(d)
print(df)

In [ ]:
prices = [299,300,4422,4455]
products = ["earbuds","Phones","Fans","tables"]
#product_prices = pd.Series(prices,index=products)
#print(product_prices)

In [ ]:
'''print(product_prices.sum())
print(product_prices.mean())
print(product_prices.max())
print(product_prices.min())
product_prices.head(2)
product_prices.tail(2)'''

NameError: name 'product_prices' is not defined

In [ ]:
print("Apply (Adding 18% GST):\n",product_prices.apply(lambda x:f'₹{x+(x*0.18)}'))

In [ ]:
print("Apply (Adding 18% GST):\n",product_prices.map(lambda x:f'₹{x}.00'))

In [ ]:
print(product_prices.sort_values())
print(product_prices.sort_index())

In [ ]:
print(product_prices.sort_values(ascending = False))

In [ ]:
print(product_prices.value_counts())

NameError: name 'product_prices' is not defined

In [ ]:
stock = {
    "Products": ["Apple", "Vivo", "Moto","Turbo"],
    "Brand": ["Vamsi", "Ramya", "srinu","Jaya"],
    "Prices": [223, 45343, 4462, 4342],
    "stock": [20, 40, 20, 10000000000000000000000000000000],
    "Best_Seller": [False, True,False, True]
    }
df = pd.DataFrame(stock)
print(df)

In [ ]:
print(df.shape)
print(df.columns)
print(df.info())

In [ ]:
df.head(2)
df.tail(2)

NameError: name 'df' is not defined

In [ ]:
print(df.loc[3,"Brand"])
print(df.iloc[3,3])

In [ ]:
print(df.iloc[2])
print(df.iloc[3])

NameError: name 'df' is not defined

In [ ]:
print(df.loc[df["Best_Seller"]==True])
print(df.loc[df["Products"]=="Turbo"])
print(df.loc[df["Prices"]>100])

In [ ]:
re_name = df.rename(columns={"Prices" : "Cost"})
print(re_name)

In [ ]:
g = df.groupby("Brand").agg({"Prices":"sum"},{"stock":"sum"})
print(g)

In [ ]:
#G = df.groupby("Brand").agg({"Prices":["mean","max","min"]})
print(G)

In [ ]:
Ratail = {
    "Products": ["Apple", "Vivo", "Moto","Turbo"],
    "Brand": ["Vamsi", "Ramya", "srinu","Jaya"],
    "Prices": [223, 45343, 4462, 4342],
    "stock": [20, 40, 20, 10000000000000000000000000000000],
    "Best_Seller": [False, True,False, True]
    }
Bf = pd.DataFrame(Ratail)
print(Bf)

In [ ]:
m = df.merge(Bf,on="Brand")
print(m)

In [ ]:
new = {
    "Products": ["Apple"],
    "Brand": ["Vamsi"],
    "Prices": [223],
    "stock": [20],
    "Best_Seller": [False]
    }
N = pd.DataFrame(new)
print(N)

In [ ]:
c = pd.concat([df,N],ignore_index=True)
print(c)

NameError: name 'pd' is not defined

In [ ]:
print(df["Brand"])

In [ ]:
df["Prices"] = df["Prices"].astype(float)
print(df["Prices"])

In [ ]:
#Bf["Rank"] = Bf["Prices"].rank(ascending=False)
#print(Bf["Rank"])
print(Bf.sort_values(by="Rank",ascending=True))

In [ ]:
import pandas as pd
df1  = pd.DataFrame({
    "ID": [1,2],
    "Name": ["Vamsi","Ramya"],
    "Age": [20,22]
})
df2  = pd.DataFrame({
    "ID": [3,4],
    "Name": ["Vasu","Ragu"],
    "Age": [20,22]
})

c = pd.concat([df1,df2],axis = 0)
print(c)

   ID   Name  Age
0   1  Vamsi   20
1   2  Ramya   22
0   3   Vasu   20
1   4   Ragu   22

In [ ]:
C = pd.concat([df1,df2],axis = 1)
print(C)

   ID   Name  Age  ID  Name  Age
0   1  Vamsi   20   3  Vasu   20
1   2  Ramya   22   4  Ragu   22

In [ ]:
Ratail = {
    "Products": ["Apple", "Vivo", "Moto","Turbo"],
    "Brand": ["Vamsi", "Ramya", "srinu","Jaya"],
    "Prices": [223, 45343, 4462, 4342],
    "stock": [20, 40, 20, 10000000000000000000000000000000],
    "Best_Seller": [False, True,False, True]
    }
df = pd.DataFrame(Ratail)
print(df)

  Products  Brand  Prices                             stock  Best_Seller
0    Apple  Vamsi     223                                20        False
1     Vivo  Ramya   45343                                40         True
2     Moto  srinu    4462                                20        False
3    Turbo   Jaya    4342  10000000000000000000000000000000         True

In [ ]:
df

  Products  Brand  Prices                             stock  Best_Seller
0    Apple  Vamsi     223                                20        False
1     Vivo  Ramya   45343                                40         True
2     Moto  srinu    4462                                20        False
3    Turbo   Jaya    4342  10000000000000000000000000000000         True

In [ ]:
f=df.pivot_table(values="Prices",index="Brand",columns="stock",aggfunc="max")
print(f)

stock      20       40  10000000000000000000000000000000
Brand
Jaya      NaN      NaN                            4342.0
Ramya     NaN  45343.0                               NaN
Vamsi   223.0      NaN                               NaN
srinu  4462.0      NaN                               NaN

In [ ]:
cros = pd.crosstab(df["Brand"],df["stock"])
print(cros)

stock  20  40  10000000000000000000000000000000
Brand
Jaya    0   0                                 1
Ramya   0   1                                 0
Vamsi   1   0                                 0
srinu   1   0                                 0

In [ ]:
import numpy as np
data = {
    "P": [np.nan,23, np.nan,54],
    "B": [65,  np.nan, 45,23],
    "c": [ np.nan, 45343,  np.nan, 4342]
    }
df = pd.DataFrame(data)
print("---------------------Original Table with Null values-------------------------\n",df)

---------------------Original Table with Null values-------------------------
       P     B        c
0   NaN  65.0      NaN
1  23.0   NaN  45343.0
2   NaN  45.0      NaN
3  54.0  23.0   4342.0

In [ ]:
df.dropna()

      P     B       c
3  54.0  23.0  4342.0

In [ ]:
f=df.fillna("Vamsi")
print(f)

       P      B        c
0  Vamsi   65.0    Vamsi
1   23.0  Vamsi  45343.0
2  Vamsi   45.0    Vamsi
3   54.0   23.0   4342.0

In [ ]:
print(df)
df.interpolate()

      P     B        c
0   NaN  65.0      NaN
1  23.0   NaN  45343.0
2   NaN  45.0      NaN
3  54.0  23.0   4342.0

      P     B        c
0   NaN  65.0      NaN
1  23.0  55.0  45343.0
2  38.5  45.0  24842.5
3  54.0  23.0   4342.0

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving email.csv to email.csv

In [ ]:
df = pd.read_csv("email.csv")
print(df)

  subramanyavarma16@gmail.com
0  nagendravarma016@gmail.com
1       rishivarmaj@gmail.com

In [ ]:
from bs4 import BeautifulSoup
import requests
URL  = 'https://timely-sunshine-e821b3.netlify.app/'
Page = requests.get(URL)
Page.status_code

200

In [ ]:
htmlCode = Page.text

In [ ]:
#print(htmlCode)
soup = BeautifulSoup(htmlCode,'html.parser')
print(soup)

<html>
<head>
<style>
            .header{
                height : 100px;
                background-color: bisque;
                box-shadow: 0px 10px 10px black;
            }
            .header p{
                font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
                font-weight: bold;
                font-size: 70px;
                text-align: center;
                padding-top:10px;
            }
            .main{
                background-color: rgb(189, 234, 234);
                display: flex;
                flex-wrap: wrap;
                justify-content: space-between;
            }
            img{
                width : 100%;
                height : 100%;
            }
            .main{
                margin-top:20px;
            }
            .a{
                height : 300px;
                width : 250px;
                background-color: burlywood;
                padding : 10px;
                margin:10px;
            }
            .a .image{
                height : 250px;
            }
            .a .name{
                font-family: Georgia, 'Times New Roman', Times, serif;
                text-align: center;
                padding-top:10px;
            }
            .a .name::before{
                content: "Name: ";
            }
            .a .price{
                font-family: Georgia, 'Times New Roman', Times, serif;
                text-align: center;
                padding-top:5px;
            }
            .a .price::before{
                content: "Price: "
            }
        </style>
</head>
<body>
<div class="header">
<p>Webscrapping Example</p>
</div>
<div class="main">
<div class="a">
<div class="image">
<img src="toy.png"/>
</div>
<div class="name">
                    Robot 1
                </div>
<div class="price">
                    100
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy2.png"/>
</div>
<div class="name">
                    Teddy 1
                </div>
<div class="price">
                    120
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy3.png"/>
</div>
<div class="name">
                    Car 1
                </div>
<div class="price">
                    99
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy.png"/>
</div>
<div class="name">
                    Robot 2
                </div>
<div class="price">
                    200
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy2.png"/>
</div>
<div class="name">
                    Teddy 2
                </div>
<div class="price">
                    220
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy3.png"/>
</div>
<div class="name">
                    Car 2
                </div>
<div class="price">
                    199
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy.png"/>
</div>
<div class="name">
                    Robot 3
                </div>
<div class="price">
                    300
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy2.png"/>
</div>
<div class="name">
                    Teddy 3
                </div>
<div class="price">
                    220
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy3.png"/>
</div>
<div class="name">
                    Car 3
                </div>
<div class="price">
                    299
                </div>
</div>
</div>
</body>
</html>

In [ ]:
c = soup.find_all('div',attrs={'class':'main'})
for i in c:
    print("Div: \n",i,end='\n\n\n')

Div:
 <div class="main">
<div class="a">
<div class="image">
<img src="toy.png"/>
</div>
<div class="name">
                    Robot 1
                </div>
<div class="price">
                    100
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy2.png"/>
</div>
<div class="name">
                    Teddy 1
                </div>
<div class="price">
                    120
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy3.png"/>
</div>
<div class="name">
                    Car 1
                </div>
<div class="price">
                    99
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy.png"/>
</div>
<div class="name">
                    Robot 2
                </div>
<div class="price">
                    200
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy2.png"/>
</div>
<div class="name">
                    Teddy 2
                </div>
<div class="price">
                    220
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy3.png"/>
</div>
<div class="name">
                    Car 2
                </div>
<div class="price">
                    199
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy.png"/>
</div>
<div class="name">
                    Robot 3
                </div>
<div class="price">
                    300
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy2.png"/>
</div>
<div class="name">
                    Teddy 3
                </div>
<div class="price">
                    220
                </div>
</div>
<div class="a">
<div class="image">
<img src="toy3.png"/>
</div>
<div class="name">
                    Car 3
                </div>
<div class="price">
                    299
                </div>
</div>
</div>

In [ ]:
content = soup.find('div',attrs={'class':'price'})
t = content.text
print(t)

                    100

In [ ]:
content = soup.find('div',attrs={'class':'price'})
t = content.text.strip()
print(t)

100

In [ ]:
content = soup.find('div',attrs={'class':'image'})
t = content.text
print(t)

In [ ]:
i = content.find('img')
print(i)

<img src="toy.png"/>

In [ ]:
im = i['src']
print(im)

toy.png

In [ ]:
item = soup.find_all('div',class_='a')
names_list = []
prices_list = []
images_list = []

for items in item:
    extracted_name = items.find('div',class_='name').text.strip()
    extracted_price = items.find('div',class_='price').text.strip()
    image_tag = items.find('div',class_='image').find('img')
    extracted_image_src = image_tag['src'] if image_tag else None

    names_list.append(extracted_name)
    prices_list.append(extracted_price)
    images_list.append(extracted_image_src)

print("Names : ", names_list)
print("Prices : ", prices_list)
print("images : ", images_list)

Names :  ['Robot 1', 'Teddy 1', 'Car 1', 'Robot 2', 'Teddy 2', 'Car 2', 'Robot 3', 'Teddy 3', 'Car 3']
Prices :  ['100', '120', '99', '200', '220', '199', '300', '220', '299']
images :  ['toy.png', 'toy2.png', 'toy3.png', 'toy.png', 'toy2.png', 'toy3.png', 'toy.png', 'toy2.png', 'toy3.png']

In [ ]:
df = pd.DataFrame({'Product_Name':names_list,"Product_Prices ":prices_list,"Product_images":images_list})

In [ ]:
df

  Product_Name Product_Prices  Product_images
0      Robot 1             100        toy.png
1      Teddy 1             120       toy2.png
2        Car 1              99       toy3.png
3      Robot 2             200        toy.png
4      Teddy 2             220       toy2.png
5        Car 2             199       toy3.png
6      Robot 3             300        toy.png
7      Teddy 3             220       toy2.png
8        Car 3             299       toy3.png

In [ ]:
df.to_csv('ProductDetails.csv',header = True, index=False)
files.download('ProductDetails.csv')